# Generated by Django 5.2.9 on 2026-01-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
