# Generated by Django 5.2.9 on 2026-06-20 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='field_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='location_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
